### PR TITLE
Update to more recent bigdataviewer-core API (WIP)

### PR DESCRIPTION
**Pull request by tpietzsch**
- Start replacing usage of `@Deprecated` BDV API
- Simplify generics:
    - remove unnecessary `X` type parameter in
       `ExplorerWindow<AS extends AbstractSpimData<?>, X extends XmlIoAbstractSpimData<?, AS>>`
       and downstream classes.
    - remove unnecessary bounds that are already implied by the super-type's generics, e.g.,
       `AbstractSpimData<? extends AbstractSequenceDescription<? extends BasicViewSetup, ? extends BasicViewDescription<?>, ? extends BasicImgLoader>>`
       adds nothing over `AbstractSpimData<?>`
- fix (hopefully) reloading of registrations in `BDVPopup`

### CODE REVIEW

**Comment by StephanPreibisch** [comment]
Screenshot 2023-11-14 at 10 13 05 AM

After setting images to 25% overlap and running the stitching, this is how it looks. Restarting BDV from within BigStitcher fixes it ...

**Comment by StephanPreibisch** [comment]
How to reproduce:
- Download: https://drive.google.com/file/d/1gH3PuNoTyhDWca9U3oUCWdC9GNyvmSiM/view?usp=sharing
- Start BigStitcher (net.preibisch.stitcher.plugin.BigStitcher main method), load XML
- Select All
- Right click > Stitch Dataset ...
- Average Channels
- 2,2,1 > OK
- Yes
- Apply & Run Global Optimization
- default "Two Round ... (5.0/7.0px)" - OK
- Press R (or zoom out yourself) > now it looks like the picture above

To fix the display then:
- right click Display in BigDataViewer (On/Off)
- right click Display in BigDataViewer (On/Off)
- Press R (or zoom out yourself)

**Comment by StephanPreibisch** [comment]
Here are the transformations as computed:
tpId=0 setupId=0: (1, 0, 0, -463.3695), (0, 1, 0, -911.4623), (0, 0, 1, 0.0045), Scaling: 1, 1, 1
tpId=0 setupId=1: (1, 0, 0, -1.1055), (0, 1, 0, -911.3427), (0, 0, 1, 0.152), Scaling: 1, 1, 1
tpId=0 setupId=2: (1, 0, 0, -461.8335), (0, 1, 0, -457.4229), (0, 0, 1, -0.0914), Scaling: 1, 1, 1
tpId=0 setupId=3: (1, 0, 0, -0.1901), (0, 1, 0, -456.0525), (0, 0, 1, 0.0867), Scaling: 1, 1, 1
tpId=0 setupId=4: (1, 0, 0, -462.0296), (0, 1, 0, 1.394), (0, 0, 1, -0.1483), Scaling: 1, 1, 1
tpId=0 setupId=5: (1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), Scaling: 1, 1, 1
tpId=0 setupId=6: (1, 0, 0, -463.3695), (0, 1, 0, -911.4623), (0, 0, 1, 0.0045), Scaling: 1, 1, 1
tpId=0 setupId=7: (1, 0, 0, -1.1055), (0, 1, 0, -911.3427), (0, 0, 1, 0.152), Scaling: 1, 1, 1
tpId=0 setupId=8: (1, 0, 0, -461.8335), (0, 1, 0, -457.4229), (0, 0, 1, -0.0914), Scaling: 1, 1, 1
tpId=0 setupId=9: (1, 0, 0, -0.1901), (0, 1, 0, -456.0525), (0, 0, 1, 0.0867), Scaling: 1, 1, 1
tpId=0 setupId=10: (1, 0, 0, -462.0296), (0, 1, 0, 1.394), (0, 0, 1, -0.1483), Scaling: 1, 1, 1
tpId=0 setupId=11: (1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), Scaling: 1, 1, 1
tpId=0 setupId=12: (1, 0, 0, -463.3695), (0, 1, 0, -911.4623), (0, 0, 1, 0.0045), Scaling: 1, 1, 1
tpId=0 setupId=13: (1, 0, 0, -1.1055), (0, 1, 0, -911.3427), (0, 0, 1, 0.152), Scaling: 1, 1, 1
tpId=0 setupId=14: (1, 0, 0, -461.8335), (0, 1, 0, -457.4229), (0, 0, 1, -0.0914), Scaling: 1, 1, 1
tpId=0 setupId=15: (1, 0, 0, -0.1901), (0, 1, 0, -456.0525), (0, 0, 1, 0.0867), Scaling: 1, 1, 1
tpId=0 setupId=16: (1, 0, 0, -462.0296), (0, 1, 0, 1.394), (0, 0, 1, -0.1483), Scaling: 1, 1, 1
tpId=0 setupId=17: (1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), Scaling: 1, 1, 1

**Comment by StephanPreibisch** [comment]
To reproduce the error, it is actually sufficient to stitch the first two tiles only:
Screenshot 2023-11-14 at 12 49 34 PM

**Comment by tpietzsch** [comment]
that problem should be fixed now

**Comment by StephanPreibisch** [comment]
Sweet, some minor things to work on, but I'll merge it for now to cut a release and fix BigStitcher, thanks @tpietzsch :)

**Pull request merged**
